### ISSUE TITLE
Component out of memory

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/s3-extractor#14]
Viz. https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2018/07/25/14/2018-07-25-14-15-59-5b5869ff21c6f-exception
Stalo se to nahodile jednou v hodinové orchestraci, která jinak běží ok (https://connection.eu-central-1.keboola.com/admin/projects/25/jobs/5217633). Možná by stálo za zvážení zvednout paměť, 256 není moc? Ale moc netuším co tam s3 sdk s tou pamětí vyrábí, tak kdo ví.

**Comment by Halama** [comment]
Dívám se že ten extractor má už od 18.6 nastaveno `1024m`, to už bych asi nezvedal.
![image](https://user-images.githubusercontent.com/903531/43382741-0e923e06-93d9-11e8-8486-3f9f8118bbab.png)

**Comment by Halama** [comment]
koukám že tohle je starý S3 extractor. Issue přesunu.

**Comment by Halama** [comment]
https://github.com/keboola/aws-s3-extractor/issues/25
