### ISSUE TITLE
Delimiter "\t" not working

### ISSUE THREAD

**Issue by ujovlado** [keboola/s3-extractor#7]
Extractor to akceptuje, no `php-csv` to nezobere kvoli dlzke a konci to chybou.

**Comment by ujovlado** [comment]
Hotfix is to type tab manually.

**Comment by ondrejhlavacek** [comment]
Je to v UI

**Comment by ondrejhlavacek** [comment]
fixed by https://github.com/keboola/kbc-ui/commit/a69e5539e9d670b87e518ed23069b57a48c0139b
