### ISSUE TITLE
Use IAM roles instead of static credentials

### ISSUE THREAD

**Issue by Halama** [keboola/s3-extractor#8]
Statický credentials nejsou doporučený, většina služeb už podporuje propojení pomocí rolí.
Náš AWS konenktery by taky měly nabízet pouze tuhle možnost.

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html

Vyžkoušet se dá např. na New Relic https://docs.newrelic.com/docs/infrastructure/amazon-integrations/getting-started/connect-aws-services-infrastructure 
nebo https://app.cloudability.com to má udělaný docela pěkně.

**Comment by ondrejhlavacek** [comment]
Nejsem si jistej, jestli to je úplně průchozí. Museli bychom možná dělat browser S3, aby si to někdo mohl prohlídnout. Optám se na globálním slacku.

**Comment by ondrejhlavacek** [comment]
Pročítám si ještě http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

> Example Corp can use any string value they want for the ExternalId, as long as it is unique for each customer. It can be a customer account number or even a random string of characters, as long as no two customers have the same value. It is not intended to be a 'secret'. Example Corp must provide the ExternalId value to each customer. What is key is that it must be generated by Example Corp and not their customers.

Takže v UI by byl link na dokumentaci a vygenerovaný ID (region - projekt - komponenta - config, nebo rovnou GUID), jestli to chápu dobře? Pak teprv může začít konfigurace u klienta. Vyplnit klienta ExternalID nemůžeme, protože by u nás mohly vzniknout duplicity.

**Comment by ondrajodas** [comment]
přesunul jsem to do Jiry s tím že bychom to udělali nějaký z následujících sprintů

https://keboola.atlassian.net/browse/COM-234
